// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAV3V81IEzGhIpjsQG8bBNToaC_CsQkRs',
    appId: '1:905439404180:web:467ba5bca8a0d0f2f79481',
    messagingSenderId: '905439404180',
    projectId: 'trmnet-8d0b3',
    authDomain: 'trmnet-8d0b3.firebaseapp.com',
    storageBucket: 'trmnet-8d0b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp6qCRwhHWBWTgqpLRk-JK44t8VTCg7UY',
    appId: '1:905439404180:android:e50ae75f6910a718f79481',
    messagingSenderId: '905439404180',
    projectId: 'trmnet-8d0b3',
    storageBucket: 'trmnet-8d0b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXhz4RL09vrhzL1LmQjsfjWI5i4_4mCmQ',
    appId: '1:905439404180:ios:c597a28ad304bf55f79481',
    messagingSenderId: '905439404180',
    projectId: 'trmnet-8d0b3',
    storageBucket: 'trmnet-8d0b3.appspot.com',
    iosBundleId: 'com.example.chatlinxs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXhz4RL09vrhzL1LmQjsfjWI5i4_4mCmQ',
    appId: '1:905439404180:ios:c597a28ad304bf55f79481',
    messagingSenderId: '905439404180',
    projectId: 'trmnet-8d0b3',
    storageBucket: 'trmnet-8d0b3.appspot.com',
    iosBundleId: 'com.example.chatlinxs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAV3V81IEzGhIpjsQG8bBNToaC_CsQkRs',
    appId: '1:905439404180:web:3236ba93acb15180f79481',
    messagingSenderId: '905439404180',
    projectId: 'trmnet-8d0b3',
    authDomain: 'trmnet-8d0b3.firebaseapp.com',
    storageBucket: 'trmnet-8d0b3.appspot.com',
  );
}
